name: Deploy to Production

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host:        ${{ secrets.SSH_HOST }}
          username:    ${{ secrets.SSH_USER }}
          key:         ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            TARGET_DIR=/root/ViveCore/

            cd "$TARGET_DIR"
            git fetch --all
            git reset --hard origin/master

            export ContainerRuntimeIdentifier=linux-arm64
            /root/.dotnet/tools/aspire publish

            docker compose up -d --remove-orphans
