name: Run all tests

on:
  push:
    branches: [ "*" ]
    
  pull_request:
    branches: [ "*" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Create .env
      run:
        touch .env && echo '${{ secrets.ENV_VARIABLES }}' > .env

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
